"""verify model metadata

Revision ID: 20afee80360a
Revises: c1a36681ae8b
Create Date: 2026-08-29 17:29:47.738170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20afee80360a'
down_revision: Union[str, Sequence[str], None] = 'c1a36681ae8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_analyses_id'), 'message_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_message_analyses_safety_label'), 'message_analyses', ['safety_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_analyses_safety_label'), table_name='message_analyses')
    op.drop_index(op.f('ix_message_analyses_id'), table_name='message_analyses')
    # ### end Alembic commands ###
