import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'core/theme/app_theme.dart';
import 'firebase_options.dart';
import 'models/message_analysis.dart';
import 'providers/auth_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/history/history_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/profile/profile_screen.dart';
import 'widgets/app_background.dart';
import 'core/services/ocr_service.dart';


// ============================================================
// APP START
// ============================================================

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ----------------------------------------------------------
  // Initialize Firebase
  //
  // firebase_options.dart is generated by:
  //
  // flutterfire configure
  // ----------------------------------------------------------

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => AuthProvider()..initialize(),
      child: const MessageShieldApp(),
    ),
  );
}

// ============================================================
// MAIN APP
// ============================================================

class MessageShieldApp extends StatelessWidget {
  const MessageShieldApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'MessageShield',
      theme: AppTheme.darkTheme,
      home: const AuthGate(),
    );
  }
}

// ============================================================
// AUTH GATE
//
// Controls the first screen when the application starts.
//
// 1. Checking saved session → Loading screen
// 2. No valid user         → Login screen
// 3. Valid user            → AppShell
// ============================================================

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthProvider>();



    if (!auth.isInitialized) {
      return const AppLoadingScreen();
    }



    if (!auth.isAuthenticated) {
      return const LoginScreen();
    }



    return const AppShell();
  }
}

// ============================================================
// APP LOADING SCREEN
// ============================================================

class AppLoadingScreen extends StatelessWidget {
  const AppLoadingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: const Center(
        child: CircularProgressIndicator(
          color: AppColors.teal,
        ),
      ),
    );
  }
}

// ============================================================
// APP SECTIONS
// ============================================================

enum AppSection {
  home,
  history,
  safety,
  profile,
}

// ============================================================
// APP SHELL
// ============================================================

class AppShell extends StatefulWidget {
  const AppShell({super.key});

  @override
  State<AppShell> createState() => _AppShellState();
}

class _AppShellState extends State<AppShell> {
  AppSection _selected = AppSection.home;

  MessageAnalysis? _latestAnalysis;



  String? _scannedText;

  // ==========================================================
  // ANALYSIS COMPLETE
  // ==========================================================

  void _handleAnalysisComplete(
    MessageAnalysis analysis,
  ) {
    setState(() {
      _latestAnalysis = analysis;
    });
  }

  // ==========================================================
  // SELECT SECTION
  // ==========================================================

  void _selectSection(
    AppSection section,
  ) {
    setState(() {
      _selected = section;
    });
  }

  // ==========================================================
  // OPEN SAFETY
  // ==========================================================

  void _openSafety(
    BuildContext context,
  ) {
    final width = MediaQuery.sizeOf(context).width;

    if (width < 700) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) =>
              const SafetyGuidelinesScreen(),
        ),
      );
    } else {
      _selectSection(AppSection.safety);
    }
  }

  // ==========================================================
  // SCAN
  // ==========================================================

  Future<void> _openScan() async {
  final source = await showModalBottomSheet<String>(
    context: context,
    backgroundColor: Colors.transparent,
    builder: (sheetContext) {
      return SafeArea(
        child: Container(
          padding: const EdgeInsets.fromLTRB(
            20,
            20,
            20,
            24,
          ),
          decoration: const BoxDecoration(
            color: Color(0xFF0D2028),
            borderRadius: BorderRadius.vertical(
              top: Radius.circular(24),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 52,
                height: 52,
                decoration: BoxDecoration(
                  color: AppColors.teal.withValues(
                    alpha: 0.12,
                  ),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: const Icon(
                  Icons.document_scanner_outlined,
                  color: AppColors.tealSoft,
                  size: 28,
                ),
              ),
              const SizedBox(height: 14),
              const Text(
                'Scan message',
                style: TextStyle(
                  color: AppColors.textPrimary,
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 8),
              const Text(
                'Capture a message with your camera '
                'or select a screenshot/image.',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: AppColors.textSecondary,
                  fontSize: 14,
                  height: 1.4,
                ),
              ),
              const SizedBox(height: 20),

              // Camera
              SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton.icon(
                  onPressed: () {
                    Navigator.pop(
                      sheetContext,
                      'camera',
                    );
                  },
                  icon: const Icon(
                    Icons.camera_alt_outlined,
                  ),
                  label: const Text(
                    'SCAN WITH CAMERA',
                    style: TextStyle(
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),

              const SizedBox(height: 12),

              // Gallery / Screenshot
              SizedBox(
                width: double.infinity,
                height: 52,
                child: OutlinedButton.icon(
                  onPressed: () {
                    Navigator.pop(
                      sheetContext,
                      'gallery',
                    );
                  },
                  icon: const Icon(
                    Icons.photo_library_outlined,
                  ),
                  label: const Text(
                    'CHOOSE IMAGE',
                    style: TextStyle(
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      );
    },
  );

  if (!mounted || source == null) {
    return;
  }

  String? extractedText;

  try {
    // ==========================================
    // Show OCR progress
    // ==========================================

    showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (_) {
        return const Center(
          child: CircularProgressIndicator(),
        );
      },
    );

    // ==========================================
    // OCR
    // ==========================================

    if (source == 'camera') {
      extractedText =
          await OcrService.scanFromCamera();
    } else if (source == 'gallery') {
      extractedText =
          await OcrService.scanFromGallery();
    }
  } catch (error, stackTrace) {
    debugPrint(
      '========================================',
    );
    debugPrint('OCR SCAN ERROR:');
    debugPrint(error.toString());
    debugPrint('OCR STACK TRACE:');
    debugPrint(stackTrace.toString());
    debugPrint(
      '========================================',
    );

    extractedText = null;

    if (mounted) {
      Navigator.of(context).pop();
    }

    if (!mounted) {
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(
          'Unable to scan the message. '
          '${error.toString().replaceFirst('Exception: ', '')}',
        ),
        backgroundColor: AppColors.danger,
        behavior: SnackBarBehavior.floating,
      ),
    );

    return;
  }

  // Close OCR progress dialog.
  if (mounted) {
    Navigator.of(context).pop();
  }

  if (!mounted) {
    return;
  }

  // ==========================================
  // No text detected
  // ==========================================

  if (extractedText == null ||
      extractedText!.trim().isEmpty) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
          'No readable text was found in the image.',
        ),
        behavior: SnackBarBehavior.floating,
      ),
    );

    return;
  }

  // ==========================================
  // Send extracted text to HomeScreen
  // ==========================================

  setState(() {
    _scannedText = extractedText!.trim();
    _selected = AppSection.home;
  });
}

  // ==========================================================
  // CURRENT PAGE
  // ==========================================================

  Widget _buildCurrentPage(
    BuildContext context,
  ) {
    switch (_selected) {
      case AppSection.home:
        return HomeScreen(
          onAnalysisComplete:
              _handleAnalysisComplete,
          onOpenSafety: () =>
              _openSafety(context),
          scannedText: _scannedText,
          onScannedTextConsumed: () {
            setState(() {
              _scannedText = null;
            });
          },
        );

      case AppSection.history:
        return const HistoryScreen();

      case AppSection.safety:
        return const SafetyGuidelinesScreen(
          embedded: true,
        );

      case AppSection.profile:
        return const ProfileScreen();
    }
  }

  // ==========================================================
  // MAIN APP SHELL UI
  // ==========================================================

  @override
  Widget build(
    BuildContext context,
  ) {
    final width =
        MediaQuery.sizeOf(context).width;

    final isMobile = width < 700;

    final isTablet =
        width >= 700 && width < 1100;

    return AppBackground(
      child: Scaffold(
        backgroundColor: Colors.transparent,

        body: isMobile
            ? SafeArea(
                bottom: false,
                child:
                    _buildCurrentPage(context),
              )
            : SafeArea(
                child: Row(
                  children: [
                    if (isTablet)
                      _SideNavigation(
                        selected: _selected,
                        onSelected:
                            _selectSection,
                        onScan: _openScan,
                        extended: false,
                      )
                    else
                      _SideNavigation(
                        selected: _selected,
                        onSelected:
                            _selectSection,
                        onScan: _openScan,
                        extended: true,
                      ),

                    Container(
                      width: 1,
                      color:
                          AppColors.teal.withValues(
                        alpha: 0.12,
                      ),
                    ),

                    Expanded(
                      child:
                          _buildCurrentPage(context),
                    ),
                  ],
                ),
              ),

        bottomNavigationBar: isMobile
            ? _buildMobileBottomNavigation()
            : null,
      ),
    );
  }

  // ==========================================================
  // MOBILE BOTTOM NAVIGATION
  // ==========================================================

  Widget _buildMobileBottomNavigation() {
    final selectedIndex = switch (_selected) {
      AppSection.home => 0,
      AppSection.history => 2,
      AppSection.safety => 0,
      AppSection.profile => 3,
    };

    return NavigationBar(
      backgroundColor: AppColors.background,
      height: 72,
      selectedIndex: selectedIndex,

      onDestinationSelected: (index) {
        switch (index) {
          case 0:
            _selectSection(
              AppSection.home,
            );
            break;

          case 1:
            _openScan();
            break;

          case 2:
            _selectSection(
              AppSection.history,
            );
            break;

          case 3:
            _selectSection(
              AppSection.profile,
            );
            break;
        }
      },

      destinations: const [
        NavigationDestination(
          icon: Icon(Icons.home_outlined),
          selectedIcon:
              Icon(Icons.home_rounded),
          label: 'Home',
        ),

        NavigationDestination(
          icon:
              Icon(Icons.document_scanner_outlined),
          selectedIcon:
              Icon(Icons.document_scanner_rounded),
          label: 'Scan',
        ),

        NavigationDestination(
          icon:
              Icon(Icons.history_outlined),
          selectedIcon:
              Icon(Icons.history_rounded),
          label: 'History',
        ),

        NavigationDestination(
          icon:
              Icon(Icons.person_outline_rounded),
          selectedIcon:
              Icon(Icons.person_rounded),
          label: 'Profile',
        ),
      ],
    );
  }
}

// ============================================================
// DESKTOP / TABLET SIDE NAVIGATION
// ============================================================

class _SideNavigation extends StatelessWidget {
  final AppSection selected;
  final ValueChanged<AppSection> onSelected;
  final VoidCallback onScan;
  final bool extended;

  const _SideNavigation({
    required this.selected,
    required this.onSelected,
    required this.onScan,
    required this.extended,
  });

  @override
  Widget build(BuildContext context) {
    return NavigationRail(
      backgroundColor: AppColors.backgroundSoft,

      extended: extended,
      minWidth: 76,
      minExtendedWidth: 220,

      indicatorColor: AppColors.teal.withValues(
        alpha: 0.18,
      ),

      selectedIconTheme: const IconThemeData(
        color: AppColors.teal,
      ),

      unselectedIconTheme: const IconThemeData(
        color: AppColors.textSecondary,
      ),

      selectedLabelTextStyle: const TextStyle(
        color: AppColors.teal,
        fontSize: 14,
        fontWeight: FontWeight.w700,
      ),

      unselectedLabelTextStyle: const TextStyle(
        color: AppColors.textSecondary,
        fontSize: 14,
        fontWeight: FontWeight.w500,
      ),

      selectedIndex: switch (selected) {
        AppSection.home => 0,
        AppSection.history => 2,
        AppSection.safety => 0,
        AppSection.profile => 3,
      },

      onDestinationSelected: (index) {
        switch (index) {
          case 0:
            onSelected(AppSection.home);
            break;

          case 1:
            onScan();
            break;

          case 2:
            onSelected(AppSection.history);
            break;

          case 3:
            onSelected(AppSection.profile);
            break;
        }
      },

      destinations: const [
        NavigationRailDestination(
          icon: Icon(Icons.home_outlined),
          selectedIcon: Icon(Icons.home_rounded),
          label: Text('Home'),
        ),

        NavigationRailDestination(
          icon: Icon(Icons.document_scanner_outlined),
          selectedIcon:
              Icon(Icons.document_scanner_rounded),
          label: Text('Scan'),
        ),

        NavigationRailDestination(
          icon: Icon(Icons.history_outlined),
          selectedIcon: Icon(Icons.history_rounded),
          label: Text('History'),
        ),

        NavigationRailDestination(
          icon: Icon(Icons.person_outline_rounded),
          selectedIcon: Icon(Icons.person_rounded),
          label: Text('Profile'),
        ),
      ],
    );
  }
}



